[project]
name = "llamasearch"
version = "0.1.0"
description = "RAG-based search application"
requires-python = ">=3.12"
authors = [
    {name = "Leo Angulo", email = "langulo@gmu.edu"},
    {name = "Georgi Zahariev", email = "gzaharie@gmu.edu"},
    {name = "Robin Hwang", email = "rhwang4@gmu.edu"},
    {name = "Mithran Mohanraj", email = "mithran.mohanraj@gmail.com"},
    {name = "Dhanush Reddy Kandukuri", email = "kandukuri.dhanush@gmail.com"},
    {name = "Shaheda Tawakalyar", email = "stawakal@gmu.edu"},
    {name = "Malek Bashagha", email = "abashagh@gmu.edu"}
]
dependencies = [
    "pytest>=8.0.0",
    "pytest-cov>=4.1.0",
    "flake8>=7.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -v --cov=llamasearch --cov-report=term-missing"
log_cli = true
log_cli_level = "INFO"

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
exclude = [".git", "__pycache__", "build", "dist"]